# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

cache: packages

r_github_packages:  
    caravagn/pio
    caravagn/easypar
    caravagn/BMix

warnings_are_errors: false
